source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UUToolbox_Example', :exclusive => true do
  pod "UUToolbox", :path => "../"
end

target 'UUToolbox_Tests', :exclusive => true do
  pod "UUToolbox", :path => "../"

  
end
